### ISSUE TITLE
Release fails

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#53]
**Describe the bug**
Release Actions always fail.

**Reproduction Steps**
1. Go to gihhub page
2. Chose **Actions**
3. Click **Release**
4. Click Runworkflow
6. Choose **Run workflow**

URL of a source Notion page that, when docu-notion accesses or converts it, shows the problem:

**A code block showing a console error**
```
$ cross-var npx docu-notion -n $PARATEXT_NOTION_INTEGRATION_TOKEN -r $PARATEXT_NOTION_ROOT_PAGE -m ./docs -i ./static/notion_imgs -p /notion_imgs/
docu-notion version 0.[11](https://github.com/sillsdev/paratext-manual/actions/runs/4956719287/jobs/8867508101#step:5:12).0
undefined
Connecting to Notion...
Stage 1: walk children of the page named 'Outline', looking for pages...
  Looking for children and links from /Paratext Manual
  Looking for children and links from /Outline
  Looking for children and links from /Training manual
  Looking for children and links from /Training-manual/Stage 1 - Drafting
  Looking for children and links from /Training-manual/Stage 2 - Team Checking
  @notionhq/client warn: request fail {
    code: 'notionhq_client_response_error',
    message: 'Request to Notion API failed with status: 504'
  }
  /home/runner/work/paratext-manual/paratext-manual/node_modules/@notionhq/client/src/errors.ts:[24](https://github.com/sillsdev/paratext-manual/actions/runs/4956719287/jobs/8867508101#step:5:25)8
    return new UnknownHTTPResponseError({
           ^
  UnknownHTTPResponseError: Request to Notion API failed with status: 504
```

**Expected behavior**
Expect the Release to run and deploy

**Screenshots**

**Additional context**
It originally crashed t Stage 3. As I was about to write-up this error I noticed a "-" in the title  of Stage 3 I deleted it and tried again now it fails on the previous stage.

BTW the command line gets further but still fails.
```
Stage 2: convert 127 Notion pages to markdown and save locally...
Reading & converting page /Training-manual/Stage-1---Drafting/Stage 1 – Overview (/Stage-1)
Reading & converting page /Training-manual/Stage-1---Drafting/2. Organising your desktop (/2.OD)
Reading & converting page /Training-manual/Stage-1---Drafting/3. Assignments and progress (/3.PP1)
C:\Users\jjpdq\Documents\paratext-manual\node_modules\node-fetch\lib\index.js:1331
                throw new TypeError('Only HTTP(S) protocols are supported');
        ^
TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (C:\Users\jjpdq\Documents\paratext-manual\node_modules\node-fetch\lib\index.js:1331:9)
    at C:\Users\jjpdq\Documents\paratext-manual\node_modules\node-fetch\lib\index.js:1432:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\jjpdq\Documents\paratext-manual\node_modules\node-fetch\lib\index.js:1429:9)
    at C:\Users\jjpdq\Documents\paratext-manual\node_modules\docu-notion\dist\images.js:134:57
    at Generator.next (<anonymous>)
    at C:\Users\jjpdq\Documents\paratext-manual\node_modules\docu-notion\dist\images.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\jjpdq\Documents\paratext-manual\node_modules\docu-notion\dist\images.js:27:12)
    at readPrimaryImage (C:\Users\jjpdq\Documents\paratext-manual\node_modules\docu-notion\dist\images.js:133:12)
```

**Comment by andrew-polk** [comment]
Emailing you directly with more information about this image processing issue.

**Comment by andrew-polk** [comment]
The user was able to release successfully.
I created #54 for the image issue.
Closing.
